version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mightytony/dayoffmanager:${GITHUB_SHA}
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

