version: '3.8'
services:
  app:
    container_name: spring_was
    restart: on-failure
    image: mightytony/dayoffmanager:${GITHUB_SHA}
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

