spring:
  datasource:
    url: jdbc:mysql://rds-dayoffmanager.c9uvzvbmvnx3.ap-northeast-2.rds.amazonaws.com:3306/dayoffmanager?serverTime=Asia/Seoul&useSSL=false
    username: tony
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # N+1
        show_sql: true
        use_sql_comments: true

  data:
    redis:
      port: 6379
      host: redis
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8

  cache:
    type: redis
    redis:
      time-to-live: 3600  # 초 단위 TTL
      cache-null-values: false


jwt:
  secret: 4800704315a5e0e160425575ae7fa00502eff8acbbe962a369d4cd60a39efaa0
  issuer: mightytonykr@gmail.com
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: true
#    mode: HTML
#    encoding: UTF-8

#swagger:
#  enable: true
#  base-package: mightytony.sideproject.dayoffmanager
#  path:
#    - /api/.*
logging:
  level:
    org.springframework:
      cache: DEBUG
      data.redis: DEBUG
    org.springframework.web.client:
      RestTemplate : warn
    root: info
  #    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

API:
  URL: https://api.odcloud.kr/api/nts-businessman/v1/validate
  SERVICE_KEY: IqDmlmBMv%2B8ecJBIEk0Ov0tKEbpxMaHvl%2BoXoS4oVObopGNqbvS9X1JDzm0WTwjWARIpqqTEYqLA8LFlrVS48w%3D%3D

  #IqDmlmBMv+8ecJBIEk0Ov0tKEbpxMaHvl+oXoS4oVObopGNqbvS9X1JDzm0WTwjWARIpqqTEYqLA8LFlrVS48w==

  #NxcABamlz1LxPmbQB0iKT7sbUwcgjvkChlZPNAWmybGKvHH0R%2BqqgttOECHW3sGYgpeRXTFPwnG0PFB7HoL4wg%3D%3D

  #NxcABamlz1LxPmbQB0iKT7sbUwcgjvkChlZPNAWmybGKvHH0R%2BqqgttOECHW3sGYgpeRXTFPwnG0PFB7HoL4wg%3D%3D
  #