spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dayoffmanager?serverTime=Asia/Seoul
    username: tony
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # N+1
        show_sql: true
        use_sql_comments: true

  data:
    redis:
      port: 6379
      host: localhost
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8


jwt:
  secret: 4800704315a5e0e160425575ae7fa00502eff8acbbe962a369d4cd60a39efaa0
  issuer: mightytonykr@gmail.com
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: true
#    mode: HTML
#    encoding: UTF-8

#swagger:
#  enable: true
#  base-package: mightytony.sideproject.dayoffmanager
#  path:
#    - /api/.*
logging:
  level:
    root: info
  #    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace




