name: CICD - Github Actions CI & Deploy to EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # JDK setting - 깃허브 액션에서 사용할 JDK 설정 (프로젝트 jdk랑 무관)
      - uses: actions/checkout@v3
      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle caching 그래들 캐싱(빌드 시간 줄이기)
      - name: 그래들 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 환경 별 yml 파일 (후에 확장을 위해)
      - name: application.yml 만들어서 넣어두기
        if: contains(github.ref, 'main')
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.YML }}" > ./application.yml
        shell: bash # 스크립트 쓸려면 적어야함

      - name: 그래들류 실행 권한 부여
        run: chmod +x gradlew

      - name: 그래들로 빌드 (no test)
        run: ./gradlew clean build -x test

      - name: 도커허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 도커 빌드 & 푸시
        if: contains(github.ref, 'main')
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_REPO }}

  deploy:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.CI.result == 'failure' }}
        run: echo "CI job이 실패했습니다."
      - name: 운영 서버에 배포
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ec2-user
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/app/
            # 서버로 docker-compose.yml 파일 복사
            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > docker-compose.yml
            # 기존 컨테이너 중지 및 제거
            sudo docker-compose down
            # 최신 이미지 다운로드 및 빌드
            sudo docker-compose pull
            # docker-compose를 사용하여 모든 서비스 실행
            sudo docker-compose up -d
            # 사용하지 않는 Docker 이미지 삭제
            sudo docker image prune -f
